// Централизованный файл для импорта всех иконок
// Используем только проверенные иконки из react-icons/hi2
import {
  HiCheck,
  HiStar,
  HiFire,
  HiShieldCheck,
  HiCube,
  HiPhone,
  HiClipboardDocument,
  HiArrowRight,
  HiCurrencyDollar,
  HiCheckCircle,
  HiClock,
  HiExclamationTriangle,
  HiLockClosed,
  HiBuildingOffice,
  HiCog6Tooth,
  HiWrenchScrewdriver,
  HiGift,
  HiLightBulb,
  HiChartBar,
  HiSquares2X2,
  HiHome,
  HiInformationCircle,
  HiDocumentText,
  HiEnvelope,
  HiMagnifyingGlass,
  HiFolder,
  HiBookOpen,
  HiDocument,
  HiUserGroup,
  HiBriefcase,
  HiAcademicCap,
  HiRocketLaunch
} from 'react-icons/hi2'

// Экспортируем все иконки для использования в компонентах
export {
  HiCheck,
  HiStar,
  HiFire,
  HiShieldCheck,
  HiCube,
  HiPhone,
  HiClipboardDocument,
  HiArrowRight,
  HiCurrencyDollar,
  HiCheckCircle,
  HiClock,
  HiExclamationTriangle,
  HiLockClosed,
  HiBuildingOffice,
  HiCog6Tooth,
  HiWrenchScrewdriver,
  HiGift,
  HiLightBulb,
  HiChartBar,
  HiSquares2X2,
  HiHome,
  HiInformationCircle,
  HiDocumentText,
  HiEnvelope,
  HiMagnifyingGlass,
  HiFolder,
  HiBookOpen,
  HiDocument,
  HiUserGroup,
  HiBriefcase,
  HiAcademicCap,
  HiRocketLaunch
}

